// Korean
export const mapColumn = {
    year:"개설년도",
    term:"개설학기",
    department:"개설학과",
    type:"과목구분",
    level:"과정구분",
    number:"과목번호",
    code:"전산코드",
    section:"분반",
    title:"과목명",
    syllabus:"강의계획서",
    AU:"AU",
    LLC:"강:실:학",
    instructor:"담당교수",
    English:"영어",
    edu4:"Edu4.0 Q",
    sizeLimit:"정원",
    size:"수강인원",
    time:"강의시간",
    classroom:"강의실",
    examTime:"시험시간",
    remarks:"비고",
    departmentCode:"학과코드",
    semesterType:"학기구분",
    lectureType:"강의유형",
    hybrid:"대면/비대면"
};